package gui.oneWayClient;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Jack
 */
public class main extends javax.swing.JFrame {
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        connected.setVisible(false);
    }
    
    public void validConnection () {
        connected.setText("✔");
        connected.setVisible(true);
    }
    
    public void invalidConnection() {
        connected.setText("✖");
        connected.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ip1 = new javax.swing.JTextField();
        connect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ip2 = new javax.swing.JTextField();
        ip3 = new javax.swing.JTextField();
        ip4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        connected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Server:");

        ip1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ip1.setText("192");
        ip1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ip1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip1KeyTyped(evt);
            }
        });

        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(".");

        ip2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ip2.setText("168");
        ip2.setEnabled(false);
        ip2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip2KeyTyped(evt);
            }
        });

        ip3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ip3.setText("137");
        ip3.setEnabled(false);
        ip3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip3KeyTyped(evt);
            }
        });

        ip4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ip4.setText("232");
        ip4.setEnabled(false);
        ip4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip4KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(".");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(".");

        connected.setText("✔");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(ip1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ip2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ip3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ip4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connected)
                .addGap(10, 10, 10)
                .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connect)
                    .addComponent(connected))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ip1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip1KeyTyped
        String text = ip1.getText();
        if (evt.getKeyChar() == '\b' && text.length() == 0) {
            text = "";
        } else {
            text = text + evt.getKeyChar();
        }
        if(!(text.length() == 0)) {
            ip2.setEnabled(true);
        } else if (text.equals("")) {
            ip2.setEnabled(false);
        }
        if (text.length() == 3) {
            ip2.requestFocusInWindow();
        }
    }//GEN-LAST:event_ip1KeyTyped

    private void ip2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip2KeyTyped
        String text = ip2.getText();
        if (evt.getKeyChar() == '\b' && text.length() == 0) {
            text = "";
        } else {
            text = text + evt.getKeyChar();
        }
        if(!(text.length() == 0)) {
            ip3.setEnabled(true);
        } else if (text.equals("")) {
            ip3.setEnabled(false);
        }
        if (text.length() == 3) {
            ip3.requestFocusInWindow();
        }
    }//GEN-LAST:event_ip2KeyTyped

    private void ip3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip3KeyTyped
        String text = ip3.getText();
        if (evt.getKeyChar() == '\b' && text.length() == 0) {
            text = "";
        } else {
            text = text + evt.getKeyChar();
        }
        if(!(text.length() == 0)) {
            ip4.setEnabled(true);
        } else if (text.equals("")) {
            ip4.setEnabled(false);
        }
        if (text.length() == 3) {
            ip4.requestFocusInWindow();
        }
    }//GEN-LAST:event_ip3KeyTyped

    private void ip1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip1KeyPressed

    }//GEN-LAST:event_ip1KeyPressed

    private void ip4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip4KeyTyped
        String text = ip4.getText();
        if (evt.getKeyChar() == '\b' && text.length() == 0) {
            text = "";
        } else {
            text = text + evt.getKeyChar();
        }
        if (text.length() == 3) {
            connect.requestFocusInWindow();
        }
    }//GEN-LAST:event_ip4KeyTyped

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        server.oneWayClient.Client connection = new server.oneWayClient.Client(ip1.getText()+"."+ip2.getText()+"."+ip3.getText()+"."+ip4.getText(), 32253);
    }//GEN-LAST:event_connectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect;
    private javax.swing.JLabel connected;
    private javax.swing.JTextField ip1;
    private javax.swing.JTextField ip2;
    private javax.swing.JTextField ip3;
    private javax.swing.JTextField ip4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
